site_name: WORLD_MODELS-JOINT-EMBEDDING PREDICTIVE ARCHITECTURES (JEPA)
site_description: Exploring Latent Spaces and Generative Agents
site_url: https://github.com/HARISKHAN-1729/world-models-docs


theme:
  name: null           
  custom_dir: theme      


nav:
  - HOME: index.md
 

# 3. CSS & JS Loading
extra_css:
  - assets/css/style.css

extra_javascript:
 
  - https://cdn.tailwindcss.com?plugins=typography
 
  - https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js
  
  - assets/js/three-bg.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  
  - assets/js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  

  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  
 
  - assets/js/mermaid-init.js


markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: false
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  
 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  
 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
